"""add_sessions_and_relationships

Revision ID: 6b02b4ec0d77
Revises: 542c5d1f91f0
Create Date: 2026-04-11 19:07:36.592599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b02b4ec0d77'
down_revision: Union[str, Sequence[str], None] = '542c5d1f91f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('skater_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_coach_skater_active', 'relationships', ['coach_id', 'skater_id'], unique=True, postgresql_where=sa.text("status != 'ended'"))
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('processed_video_url', sa.String(length=500), nullable=True),
    sa.Column('poses_url', sa.String(length=500), nullable=True),
    sa.Column('csv_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('phases', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_element_type'), 'sessions', ['element_type'], unique=False)
    op.create_index('ix_sessions_user_element_created', 'sessions', ['user_id', 'element_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('session_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('prev_best', sa.Float(), nullable=True),
    sa.Column('reference_value', sa.Float(), nullable=True),
    sa.Column('is_in_range', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_metrics_metric_name'), 'session_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_session_metrics_session_id'), 'session_metrics', ['session_id'], unique=False)
    op.create_index('uq_session_metric_name', 'session_metrics', ['session_id', 'metric_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_session_metric_name', table_name='session_metrics')
    op.drop_index(op.f('ix_session_metrics_session_id'), table_name='session_metrics')
    op.drop_index(op.f('ix_session_metrics_metric_name'), table_name='session_metrics')
    op.drop_table('session_metrics')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_element_created', table_name='sessions')
    op.drop_index(op.f('ix_sessions_element_type'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_coach_skater_active', table_name='relationships', postgresql_where=sa.text("status != 'ended'"))
    op.drop_table('relationships')
    # ### end Alembic commands ###
