"""add_music_fingerprint

Revision ID: 7c318ee90e4a
Revises: 7e23d891c6d7
Create Date: 2026-04-19 14:48:22.268569

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c318ee90e4a"
down_revision: str | Sequence[str] | None = "7e23d891c6d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connections",
        "connection_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("COACHING", "CHOREOGRAPHY", name="connectiontype"),
        existing_nullable=False,
        existing_server_default=sa.text("'coaching'::character varying"),
    )
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("INVITED", "ACTIVE", "ENDED", name="connectionstatus"),
        existing_nullable=False,
    )
    op.add_column("music_analyses", sa.Column("fingerprint", sa.String(length=32), nullable=True))
    op.create_index(
        op.f("ix_music_analyses_fingerprint"), "music_analyses", ["fingerprint"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_music_analyses_fingerprint"), table_name="music_analyses")
    op.drop_column("music_analyses", "fingerprint")
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.Enum("INVITED", "ACTIVE", "ENDED", name="connectionstatus"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "connections",
        "connection_type",
        existing_type=sa.Enum("COACHING", "CHOREOGRAPHY", name="connectiontype"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'coaching'::character varying"),
    )
    # ### end Alembic commands ###
